### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'scalar_summary'

### ISSUE THREAD

**Issue by 2007anu-zz** [udacity/dlnd-issue-reports#151] opened 2017-02-18 17:40 UTC

**Comment by clapollo** [comment] 2017-02-19 22:44
Can you please provide more details in your error reports? Where are you seeing this error?

**Comment by 2007anu-zz** [comment] 2017-02-20 15:58
Dear Concern,

The error is coming for 'Intro to TFlearn' - Sentimental Analysis Solution.

PFA the code.

Also, below is the line for which the error is coming:


*model = build_model()*



Regards
Anuj Gupta
9953003063
Follow: www.flarrio.com
Willing to explore myself in the world of technology

**Comment by 2007anu-zz** [comment] 2017-02-24 04:57
Hi Team..

Its been 4 days...Could you please assist in resolving the error.

Regards
Anuj Gupta
9953003063
Follow: www.flarrio.com
Willing to explore myself in the world of technology

**Comment by clapollo** [comment] 2017-02-24 06:44
What version of TensorFlow are you using? What version of TFLearn? I have tried running this with multiple versions and I have been unable to reproduce the error.

**Comment by 2007anu-zz** [comment] 2017-02-24 07:02
These are the versions:

tensorflow-gpu (1.0.0)
tflearn (0.2.2)

Regards
Anuj Gupta
9953003063
Follow: www.flarrio.com
Willing to explore myself in the world of technology

**Comment by clapollo** [comment] 2017-02-24 07:08
Ah, that may be the problem. There was a little time between when they released the newest TensorFlow and the newest TFLearn and you seem to have installed during that time so your TFLearn does not match. The latest version of TFLearn is 0.3. I would recommend upgrading and seeing if that fixes the problem. You may be able to just type `pip upgrade TFLearn`, but if that doesn't work you should try `pip uninstall TFLearn` followed by `pip install TFLearn` and hopefully it will install the latest version.

Please let me know if that helps. Thank you!

**Comment by 2007anu-zz** [comment] 2017-02-24 07:34
As of now..the solution is working with Jupyter notebook. But when I run
the same on Spyder (an IDE to run python files and it is combined with
Miniconda3) the error persists. In spyder , i have installed the versions
as per your recommendation.

Regards
Anuj Gupta
9953003063
Follow: www.flarrio.com
Willing to explore myself in the world of technology

**Comment by clapollo** [comment] 2017-02-24 07:40
Ok, that's great that it's working at least in the notebook. Sorry, I'm not familiar with Spyder so I can't help with that configuration. I'm going to close this issue since we now know it's not a bug in the content. Thank you for your patience and sorry for the delay!

**Comment by 2007anu-zz** [comment] 2017-02-24 07:41
Sure...Thanks so much for your time as well.

Regards
Anuj Gupta
9953003063
Follow: www.flarrio.com
Willing to explore myself in the world of technology

**Closed as completed by clapollo** 2017-02-24 07:40 UTC
