### ISSUE TITLE
Bias initialized as random value

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#183] opened 2017-03-06 02:10 UTC
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/43289903-8d8b-49fb-9a19-5baa4aabc2d7/lessons/6ec4ffd6-4f5c-4b88-bdf6-f169119834f0/concepts/cbcb68d7-7575-442c-82d4-f796ad82b00a

Bias is an affine transformation in neural networks. Therefore it needs to be defined as a constant.

Here's a reference; http://stackoverflow.com/questions/2480650/role-of-bias-in-neural-networks

**Comment by clapollo** [comment] 2017-03-06 02:33
I'm not sure what you are saying is incorrect here. Some people will initialize biases to zero and others will use random values, but no matter what you do it needs to be a variable so that the network can change the value during training. Can you please elaborate?

**Comment by rahul-ahuja** [comment] 2017-03-06 02:50
I think Bias is initialize as a constant term which can be updated by backprop.  
It's same as in simple linear regression;

y = ax + b 
'b' here is alway a constant.

here's another reference;

https://www.quora.com/What-is-bias-in-artificial-neural-network

It's just that I have never seen bias initialized as random term anywhere else.

**Comment by rahul-ahuja** [comment] 2017-03-06 02:52
maybe that simple regression example was wrong...

**Comment by clapollo** [comment] 2017-03-06 03:05
There is no such thing as a constant term that can be updated. By definition, a constant cannot change. The network has to be able to change the value to figure out what the correct biases are, which is why we create a Variable object. 

I'm closing this issue as this is not a bug.

**Closed as completed** 2017-03-06 03:05 UTC
