### ISSUE TITLE
Incorrect command in Style Transfer

### ISSUE THREAD

**Issue by aroop** [udacity/dlnd-issue-reports#34] opened 2017-01-28 23:40 UTC
When rain princess checkpoint file is downloaded the file is named rain-princess.ckpt hence the following command is not running

python evaluate.py --checkpoint ./rain_princess.ckpt --in-path <path_to_input_file> --out-path ./output_image.jpg

Please update the command to python evaluate.py --checkpoint ./rain-princess.ckpt --in-path <path_to_input_file> --out-path ./output_image.jpg

**Comment by jwrubel** [comment] 2017-01-29 02:51
:+1: I just ran across this as well.

**Comment by jwrubel** [comment] 2017-01-29 02:52
Oh, this is a dupe of #20.

**Comment by mcleonard** [comment] 2017-01-30 00:13
It turns out that the checkpoint files we link on the page all have dashes and the checkpoint files you can download from the Google drive have underscores. So...

I made a note in the text to notify people of this. I believe the CDN we're using automatically changes underscores to dashes, so I don't think there is much we can do on our side.

**Closed as completed** 2017-01-30 00:14 UTC
